# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'getstarted.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(706, 475)
        Form.setStyleSheet("border-radius: 30px;")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(0, 0, 704, 475))
        self.label.setStyleSheet("border-image: url(:/images/img/getStarted.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.mulaibtn = QtWidgets.QPushButton(Form)
        self.mulaibtn.setGeometry(QtCore.QRect(250, 420, 190, 40))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(87)
        self.mulaibtn.setFont(font)
        self.mulaibtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.mulaibtn.setStyleSheet("font: 11pt \"Poppins\";\n"
"font-weight: 700;\n"
"border-radius: 8px;\n"
"background: #EF2B2B;\n"
"color:#ffffff;\n"
"cursor: Pointing Hand;")
        self.mulaibtn.setObjectName("mulaibtn")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.mulaibtn.setText(_translate("Form", "M U L A I"))
import res_rc
