# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainDashboard.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 600)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 800, 90))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(0, 0, 800, 90))
        self.label.setStyleSheet("border-image: url(:/images/img/header.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(0, 90, 150, 511))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 150, 511))
        self.label_2.setStyleSheet("border-image: url(:/images/img/Navbar.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.dmahasiswabtn = QtWidgets.QPushButton(self.frame_3)
        self.dmahasiswabtn.setGeometry(QtCore.QRect(10, 30, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.dmahasiswabtn.setFont(font)
        self.dmahasiswabtn.setStyleSheet("font: 9pt \"Poppins\";\n"
"\n"
"QPushButton #pushButton {\n"
"    background-color: qlineargradient(\n"
"        spread:pad, \n"
"        x1:0, y1:0, \n"
"        x2:1, y2:0, \n"
"        stop:0 rgba(11, 131, 120, 219), \n"
"        stop:1 rgba(85, 98, 112, 226)\n"
"    );\n"
"    color: rgba(255, 255, 255, 210);\n"
"    border-radius: 5px;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton #pushButton:hover {\n"
"    background-color: qlineargradient(\n"
"        spread:pad, \n"
"        x1:0, y1:0, \n"
"        x2:1, y2:0, \n"
"        stop:0 rgba(150, 123, 111, 219), \n"
"        stop:1 rgba(85, 81, 84, 226)\n"
"    );\n"
"}\n"
"\n"
"QPushButton #pushButton:pressed {\n"
"    padding-left: 5px;\n"
"    padding-top: 5px;\n"
"    background-color: rgba(150, 123, 111, 255);\n"
"}")
        self.dmahasiswabtn.setObjectName("dmahasiswabtn")
        self.laporanbtn = QtWidgets.QPushButton(self.frame_3)
        self.laporanbtn.setGeometry(QtCore.QRect(10, 60, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.laporanbtn.setFont(font)
        self.laporanbtn.setStyleSheet("font: 9pt \"Poppins\";\n"
"\n"
"QPushButton #pushButton {\n"
"    background-color: qlineargradient(\n"
"        spread:pad, \n"
"        x1:0, y1:0, \n"
"        x2:1, y2:0, \n"
"        stop:0 rgba(11, 131, 120, 219), \n"
"        stop:1 rgba(85, 98, 112, 226)\n"
"    );\n"
"    color: rgba(255, 255, 255, 210);\n"
"    border-radius: 5px;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton #pushButton:hover {\n"
"    background-color: qlineargradient(\n"
"        spread:pad, \n"
"        x1:0, y1:0, \n"
"        x2:1, y2:0, \n"
"        stop:0 rgba(150, 123, 111, 219), \n"
"        stop:1 rgba(85, 81, 84, 226)\n"
"    );\n"
"}\n"
"\n"
"QPushButton #pushButton:pressed {\n"
"    padding-left: 5px;\n"
"    padding-top: 5px;\n"
"    background-color: rgba(150, 123, 111, 255);\n"
"}")
        self.laporanbtn.setObjectName("laporanbtn")
        self.logoutbtn = QtWidgets.QPushButton(self.frame_3)
        self.logoutbtn.setGeometry(QtCore.QRect(10, 460, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.logoutbtn.setFont(font)
        self.logoutbtn.setStyleSheet("font: 9pt \"Poppins\";\n"
"\n"
"QPushButton #pushButton {\n"
"    background-color: qlineargradient(\n"
"        spread:pad, \n"
"        x1:0, y1:0, \n"
"        x2:1, y2:0, \n"
"        stop:0 rgba(11, 131, 120, 219), \n"
"        stop:1 rgba(85, 98, 112, 226)\n"
"    );\n"
"    color: rgba(255, 255, 255, 210);\n"
"    border-radius: 5px;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton #pushButton:hover {\n"
"    background-color: qlineargradient(\n"
"        spread:pad, \n"
"        x1:0, y1:0, \n"
"        x2:1, y2:0, \n"
"        stop:0 rgba(150, 123, 111, 219), \n"
"        stop:1 rgba(85, 81, 84, 226)\n"
"    );\n"
"}\n"
"\n"
"QPushButton #pushButton:pressed {\n"
"    padding-left: 5px;\n"
"    padding-top: 5px;\n"
"    background-color: rgba(150, 123, 111, 255);\n"
"}")
        self.logoutbtn.setObjectName("logoutbtn")
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setGeometry(QtCore.QRect(150, 570, 651, 30))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_3 = QtWidgets.QLabel(self.frame_4)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 651, 30))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("border-image: url(:/images/img/Footer.png);")
        self.label_3.setObjectName("label_3")
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setGeometry(QtCore.QRect(150, 90, 651, 481))
        self.frame_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.widget = QtWidgets.QWidget(self.frame_5)
        self.widget.setGeometry(QtCore.QRect(10, 10, 631, 461))
        self.widget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget.setObjectName("widget")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(240, 190, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("font: 12pt \"Poppins\";")
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.dmahasiswabtn.setText(_translate("Dialog", "DATA MAHASISWA"))
        self.laporanbtn.setText(_translate("Dialog", "LAPORAN"))
        self.logoutbtn.setText(_translate("Dialog", "LOG OUT"))
        self.label_3.setText(_translate("Dialog", " © 2025 Universitas Islam Kalimantan (UNISKA). Sistem Informasi Pengolaan Data Mahasiswa. Semua hak dilindungi"))
        self.label_4.setText(_translate("Dialog", "Jumlah Masiswa: ..."))
import res_rc
